# Generated by Django 2.1.7 on 2021-09-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matchid', models.CharField(blank=True, default=138504921999467292, max_length=100, unique=True)),
                ('GameMood', models.CharField(choices=[('CLASH_SQUAD', 'CLASH SQUAD'), ('CLASSIC', 'CLASSIC')], default='CLASSIC', max_length=120)),
                ('map', models.CharField(choices=[('BERMUDA', 'KALAHARI'), ('BERMUDA', 'BERMUDA')], default='BERMUDA', max_length=50)),
                ('ammu', models.CharField(choices=[('limited', 'LIMITED'), ('unlimited', 'UNLIMITED')], default='Limited', max_length=20)),
                ('time', models.CharField(choices=[('10am', '10AM'), ('2am', '2AM')], default='00PM', max_length=20)),
                ('entryfee', models.FloatField(choices=[(15.0, 15), (50.0, 50), (100.0, 100.0)], default=15.0)),
            ],
        ),
        migrations.CreateModel(
            name='playerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=120)),
                ('game_id', models.IntegerField()),
            ],
        ),
    ]
