# Generated by Django 2.1.7 on 2021-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freefire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinfo',
            old_name='game_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='password',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='Matchid',
            field=models.CharField(blank=True, default=138506629503009900, max_length=100, unique=True),
        ),
    ]
