# Generated by Django 2.1.7 on 2021-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freefire', '0003_auto_20210911_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Matchid',
            field=models.CharField(blank=True, default=138506634505518872, max_length=100, unique=True),
        ),
    ]
