# Generated by Django 2.1.7 on 2021-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='ammu',
            field=models.CharField(choices=[('limited', 'LIMITED'), ('unlimited', 'UNLIMITED')], default='Limited', max_length=20),
        ),
        migrations.AlterField(
            model_name='matches',
            name='GameMood',
            field=models.CharField(choices=[('CLASH_SQUAD', 'CLASH SQUAD'), ('CLASSIC', 'CLASSIC'), ('1', '1')], default='CLASSIC', max_length=120),
        ),
        migrations.AlterField(
            model_name='matches',
            name='map',
            field=models.CharField(choices=[('BERMUDA', 'KALAHARI'), ('BERMUDA', 'BERMUDA')], default='BERMUDA', max_length=50),
        ),
    ]
