# Generated by Django 2.1.7 on 2021-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210909_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='time',
            field=models.CharField(choices=[('10am', '10AM'), ('2am', '2AM')], default='00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='matches',
            name='GameMood',
            field=models.CharField(choices=[('CLASH_SQUAD', 'CLASH SQUAD'), ('CLASSIC', 'CLASSIC')], default='CLASSIC', max_length=120),
        ),
    ]
