# Generated by Django 2.1.7 on 2021-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210909_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='Matchid',
            field=models.CharField(blank=True, default=138504911906230935, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='entryfee',
            field=models.FloatField(choices=[(15.0, 15), (50.0, 50), (100.0, 100.0)], default=15.0),
        ),
    ]
