# Generated by Django 2.1.7 on 2021-09-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210909_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='Matchid',
            field=models.CharField(blank=True, default=138504913574701004, max_length=100, unique=True),
        ),
    ]
